### ISSUE TITLE
Fails when run with Jest with 2 tests

### ISSUE THREAD

**Issue by dennismphil** [saikrishna321/taiko-diagnostics#123]
# Description

This fails with Jest when there are startTracing is called twice. The stream is not closed correctly.

## Error
```
SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)

      at TracingHandler._readIOStream (node_modules/taiko-diagnostics/lib/tracingHandler.js:111:21)
      at endTracing (node_modules/taiko-diagnostics/lib/index.js:60:3)
```

## Test Code
```js
import {
    diagnostics,
    goto,
    waitFor
} from 'taiko';

const {
    startTracing,
    endTracing,
    getPerformanceMetrics
} = diagnostics;

import { globalSetup, globalTearDown } from './common/func-test-utils';

describe('Performance Measurement Tests', () => {
    beforeAll(async () => {
        await globalSetup();
    });

    afterAll(globalTearDown);

    it('should measure page load time of google', async () => {
        await startTracing();

        // Workaround for Bug in taiko diagnostics.
        // Submitted a PR. To be removed when this gets merged
        // https: //github.com/saikrishna321/taiko-diagnostics/pull/122
        await waitFor(5000);
        await goto(`www.google.com`);
        await endTracing();

        const performanceMetrics = await getPerformanceMetrics();
        console.log(performanceMetrics);
    });

    it('should measure page load time of bing', async () => {
        await startTracing();

        // Workaround for Bug in taiko diagnostics.
        // Submitted a PR. To be removed when this gets merged
        // https: //github.com/saikrishna321/taiko-diagnostics/pull/122
        await waitFor(5000);
        await goto(`www.bing.com`);
        await endTracing();

        const performanceMetrics = await getPerformanceMetrics();
        console.log(performanceMetrics);
    });
});
```

## Detailed Error
```
 console.log src/func-tests/performance1.test.js:45
    {
      firstPaint: 471.934,
      firstContentfulPaint: 471.936,
      firstMeaningfulPaint: 596.731,
      domContentLoaded: 572.176,
      timeToFirstInteractive: null,
      load: 1378.625
    }

FAIL src/func-tests/performance1.test.js (18.872s)
  Performance Measurement Tests
    ✓ should measure page load time of google (10055ms)
    ✕ should measure page load time of bing (5741ms)

  ● Performance Measurement Tests › should measure page load time of bing

    SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)

      at TracingHandler._readIOStream (node_modules/taiko-diagnostics/lib/tracingHandler.js:111:21)
      at endTracing (node_modules/taiko-diagnostics/lib/index.js:60:3)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        19.903s
```

**Comment by saikrishna321** [comment]
@dennismphil Thanks for reporting and raising a PR. I have released a new version `0.3.1` Can you please give it a try.

**Comment by dennismphil** [comment]
@saikrishna321 Thanks for the review and merging.

This issue I reported is a separate one from the PR that I raised.

**Comment by saikrishna321** [comment]
@dennismphil I'm unable to reproduce this issue.

**Comment by dennismphil** [comment]
Updated the description with the exact code with the new version

```
$ npm view taiko-diagnostics version            
0.3.1

$ npm view taiko version            
1.0.0
```

The issue still persists for me. 

When I run the test getting the same error

<img width="886" alt="Screen Shot 2019-09-28 at 9 46 07 PM" src="https://user-images.githubusercontent.com/4141366/65826416-7eceb500-e239-11e9-9c84-e12c12d89d3f.png">

**Comment by saikrishna321** [comment]
@dennismphil I'm unable to reproduce this with integration test https://github.com/saikrishna321/taiko-diagnostics/blob/master/integration/__tests__/Tracing.spec.js

Can you please give help me with more info? How is ur test different from the integration test

**Comment by dennismphil** [comment]
The difference is the `beforeEach` vs `beforeAll`

https://github.com/saikrishna321/taiko-diagnostics/blob/master/integration/__tests__/Tracing.spec.js#L12

If we open the browser beforeEach, it is like running them independently. If you change this to `beforeAll` my guess is we will see this happening

**Comment by saikrishna321** [comment]
@dennismphil Thanks for detail info. Will look into it. Let me look at the `openBrowser` API as well.

**Comment by saikrishna321** [comment]
@dennismphil tracing could be started only once per browser. I will update the ReadMe.

So in your case, please make sure to call `startTracing` only once per the lifetime of browser.

**Comment by dennismphil** [comment]
@saikrishna321 Thank you. Can we use a flag in the constructor and throw an error with this message that tracing can be started only once per the lifetime of a browser. The json parse error is slightly confusing.

**Comment by saikrishna321** [comment]
Will do that. I have updated the ReadMe already.
